### ISSUE TITLE
Idea: improve hardcoded types by using Two Slash queries

### ISSUE THREAD

**Issue by MarceloPrado** [ethanniser/effect-workshop#2]
Hi @ethanniser! 
I'm excited to go through the workshop you put, thanks for the effort and for sharing your knowledge with us. 

First and foremost, I saw from your YT video you're still in high-school. **What!?** This is really impressive. The quality level of your content is incredibly high, and I couldn't believe it when I heard you were still in school. Keep up the good work man, you're going to achieve greats things!

Now to the actual point. This isn't really an issue, just an idea to make your life easier for future videos/workshops. I'm not sure if you heard about "two slash comments", but the [Twoslash Query Comments](https://github.com/orta/vscode-twoslash-queries) (`Orta.vscode-twoslash-queries`) extension automatically adds the resolved types to your variables. Here's a small demo:

https://github.com/ethanniser/effect-workshop/assets/8047841/49dc2b37-4cda-49ed-9fbb-83747b5203ef

As long as the caret `^` aligns, the extension should work.

There's only this [issue](https://github.com/orta/vscode-twoslash-queries/issues/38) preventing the extension from working great in your setup. It trims the type past 120 characters, which is too short for Effect types. If you're feeling adventurous, I believe the author is opened for a contribution to either make this fill the available editor width, or allow changing to a different value.

Hope this helps!
Thanks again for the great work

**Comment by ethanniser** [comment]
thanks for bringing this up, ive used this in ts playground before
didnt know there was a vscode command to automatically place the comment at the right place in the line
totally see myself using this in the future

one of my goals for the files in this repo was make it so they are useful even without the accompanying video or even an editor

ultimately adding this would take away that last point
and frankly I think the types in this repo are simple enough where just the comments are fine
